---
title: "Final Project Visuals LA Crime"
output: html_document
date: "2023-12-08"
---

```{r}
lacrime <- read.csv('lacrime (1).csv')
```

```{r}
# Install and load required packages
#install.packages("ggplot2")
library(ggplot2)

# Assuming your data frame is named 'lacrime'
# Convert Vict.Descent to a new column 'EthnicityGroup' based on the specified criteria
lacrime$EthnicityGroup <- ifelse(lacrime$Vict.Descent %in% c("A", "C", "F", "J", "K", "V"), "Asian",
                                  ifelse(lacrime$Vict.Descent == "B", "Black",
                                         ifelse(lacrime$Vict.Descent == "H", "Hispanic",
                                                ifelse(lacrime$Vict.Descent == "I", "American Indian",
                                                       ifelse(lacrime$Vict.Descent == "O", "Others",
                                                              ifelse(lacrime$Vict.Descent == "W", "White", lacrime$Vict.Descent)
                                                       )
                                                )
                                         )
                                  )
)

# Filter data for Asian ethnicity and exclude the year 2022
asian_data <- lacrime[lacrime$Ethnicity == "Asian" & lacrime$Year %in% c(2020, 2021), ]

# Create a bar chart with modified x-axis and light pink color
gg <- ggplot(asian_data, aes(x = as.factor(Year), fill = factor(Year))) +
  geom_bar(color = "black", fill = "lightblue") +
  scale_x_discrete(breaks = c("2020", "2021")) +
  labs(title = "Total Number of Asian Victims by Year",
       x = "Year",
       y = "Total Number of Victims") +
  theme_minimal()

# Create a bar chart with modified data labels (with commas and decimal places)
gg + geom_text(
  aes(label = sprintf("%s (%.1f%%)", format(..count.., big.mark = ","), ..count.. / sum(..count..) * 100)),
  position = position_stack(vjust = 0.5),
  stat = "count",
  color = "black"
)



```
```{r}
# Install and load required packages
#install.packages("ggplot2")
library(ggplot2)

# Assuming your data frame is named 'lacrime'
# Convert Vict.Descent to a new column 'EthnicityGroup' based on the specified criteria
lacrime$EthnicityGroup <- ifelse(lacrime$Vict.Descent %in% c("A", "C", "F", "J", "K", "V"), "Asian",
                                  ifelse(lacrime$Vict.Descent == "B", "Black",
                                         ifelse(lacrime$Vict.Descent == "H", "Hispanic",
                                                ifelse(lacrime$Vict.Descent == "I", "American Indian",
                                                       ifelse(lacrime$Vict.Descent == "O", "Others",
                                                              ifelse(lacrime$Vict.Descent == "W", "White", lacrime$Vict.Descent)
                                                       )
                                                )
                                         )
                                  )
)

# Filter data for Asian ethnicity and exclude the year 2022
black_data <- lacrime[lacrime$Ethnicity == "Black" & lacrime$Year %in% c(2020, 2021), ]

# Create a bar chart with modified x-axis and light pink color
gg <- ggplot(black_data, aes(x = as.factor(Year), fill = factor(Year))) +
  geom_bar(color = "black", fill = "Gray") +
  scale_x_discrete(breaks = c("2020", "2021")) +
  labs(title = "Total Number of Black Victims by Year",
       x = "Year",
       y = "Total Number of Victims") +
  theme_minimal()

# Create a bar chart with modified data labels (with commas and decimal places)
gg + geom_text(
  aes(label = sprintf("%s (%.1f%%)", format(..count.., big.mark = ","), ..count.. / sum(..count..) * 100)),
  position = position_stack(vjust = 0.5),
  stat = "count",
  color = "black"
)

```

```{r}
# Install and load required packages
#install.packages("ggplot2")
library(ggplot2)

# Assuming your data frame is named 'lacrime'
# Convert Vict.Descent to a new column 'EthnicityGroup' based on the specified criteria
lacrime$EthnicityGroup <- ifelse(lacrime$Vict.Descent %in% c("A", "C", "F", "J", "K", "V"), "Asian",
                                  ifelse(lacrime$Vict.Descent == "B", "Black",
                                         ifelse(lacrime$Vict.Descent == "H", "Hispanic",
                                                ifelse(lacrime$Vict.Descent == "I", "American Indian",
                                                       ifelse(lacrime$Vict.Descent == "O", "Others",
                                                              ifelse(lacrime$Vict.Descent == "W", "White", lacrime$Vict.Descent)
                                                       )
                                                )
                                         )
                                  )
)

# Filter data for Asian ethnicity and exclude the year 2022
white_data <- lacrime[lacrime$Ethnicity == "White" & lacrime$Year %in% c(2020, 2021), ]

# Create a bar chart with modified x-axis and light pink color
gg <- ggplot(white_data, aes(x = as.factor(Year), fill = factor(Year))) +
  geom_bar(color = "black", fill = "White") +
  scale_x_discrete(breaks = c("2020", "2021")) +
  labs(title = "Total Number of White Victims by Year",
       x = "Year",
       y = "Total Number of Victims") +
  theme_minimal()

# Create a bar chart with modified data labels (with commas and decimal places)
gg + geom_text(
  aes(label = sprintf("%s (%.1f%%)", format(..count.., big.mark = ","), ..count.. / sum(..count..) * 100)),
  position = position_stack(vjust = 0.5),
  stat = "count",
  color = "black"
)


```

```{r}
# Install and load required packages
#install.packages(c("ggplot2", "lubridate", "scales"))
library(ggplot2)
library(lubridate)
library(scales)

# Convert DATE.OCC to a Date object
lacrime$DATE.OCC <- as.Date(lacrime$DATE.OCC, format = "%m/%d/%Y")

# Filter the data on Asian ethnicity and exclude the year 2022
asian_data <- lacrime[lacrime$Vict.Descent %in% c("A", "C", "F", "J", "K", "V") & year(lacrime$DATE.OCC) != 2022, ]

# Create a new column 'MonthYear' by combining Month and Year
asian_data$MonthYear <- format(asian_data$DATE.OCC, "%Y-%m")

# Create a bar chart with light blue color and labels with commas, remove the legend
ggplot(asian_data, aes(x = MonthYear, fill = "lightblue")) +
  geom_bar() +
  geom_text(stat = "count", aes(label = comma(after_stat(count))), vjust = -0.5) +
  labs(title = "Total Number of Asian Victims by Month and Year",
       x = "Month-Year",
       y = "Total Number of Victims") +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = "lightblue")

```
```{r}
# Convert DATE.OCC to a Date object
lacrime$DATE.OCC <- as.Date(lacrime$DATE.OCC, format = "%m/%d/%Y")

# Filter the data on Black ethnicity and exclude the year 2022
black_data <- lacrime[lacrime$Vict.Descent %in% c("B") & year(lacrime$DATE.OCC) != 2022, ]

# Create a new column 'MonthYear' by combining Month and Year
black_data$MonthYear <- format(black_data$DATE.OCC, "%Y-%m")

# Create a bar chart with gray fill color and labels with commas, remove the legend
ggplot(black_data, aes(x = MonthYear, fill = "Gray")) +
  geom_bar() +
  geom_text(stat = "count", aes(label = comma(after_stat(count))), vjust = -0.5) +
  labs(title = "Total Number of Black Victims by Month and Year",
       x = "Month-Year",
       y = "Total Number of Victims") +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = "gray")


```

```{r}
# Convert DATE.OCC to a Date object
lacrime$DATE.OCC <- as.Date(lacrime$DATE.OCC, format = "%m/%d/%Y")

# Filter the data on White ethnicity and exclude the year 2022
white_data <- lacrime[lacrime$Vict.Descent %in% c("W") & year(lacrime$DATE.OCC) != 2022, ]

# Create a new column 'MonthYear' by combining Month and Year
white_data$MonthYear <- format(white_data$DATE.OCC, "%Y-%m")

# Create a bar chart with gray fill color and labels with commas, remove the legend
ggplot(white_data, aes(x = MonthYear, fill = "lightpink")) +
  geom_bar() +
  geom_text(stat = "count", aes(label = comma(after_stat(count))), vjust = -0.5) +
  labs(title = "Total Number of White Victims by Month and Year",
       x = "Month-Year",
       y = "Total Number of Victims") +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = "lightpink")
```
```{r}
#lacrime <- lacrime[2:148206, ]
lacrime$Vict.Descent[lacrime$Vict.Descent == ""] <- "X"
lacrime$Vict.Descent[lacrime$Vict.Descent == "C"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "F"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "J"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "K"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "V"] <- "A"

filtered_data <- lacrime %>% filter(Vict.Descent == "A")

dates_for_letter_A <- filtered_data$DATE.OCC

filtered_data$DATE.OCC <- as.Date(filtered_data$DATE.OCC)

summary_data <- filtered_data %>%
  group_by(DATE.OCC) %>%
  summarize(Count = n())

plot(summary_data$DATE.OCC, summary_data$Count, type = "p", pch = 1, cex = 0.4,
     col = "blue", xlab = "Date Occurred", ylab = "Number of Victims", 
     main = "Number of Asian Victims Daily in Los Angeles 2020", mgp = c(3, 1, 0),
     xaxt = "n", yaxt = "n")
axis(1, at = seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), 
     labels = format(seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), "%b %Y"), cex.axis = 0.4)
axis(2, las = 0, cex.axis = 0.4)

lockdown_date <- as.Date("2020-03-19")
text(x = lockdown_date, y = max(summary_data$Count), labels = "Lockdown 3/19", pos = 1, offset = 1, cex = 0.4)

travel_ban <- as.Date("2020-01-31")
text(x = travel_ban, y = 39, labels = "Travel Ban 1/31", pos = 1, offset = 1, cex = 0.4)

model <- lm(summary_data$Count ~ as.numeric(summary_data$DATE.OCC))
abline(model, col = "red")
```
```{r}
#lacrime <- lacrime[2:148206, ]
lacrime$Vict.Descent[lacrime$Vict.Descent == ""] <- "X"
lacrime$Vict.Descent[lacrime$Vict.Descent == "C"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "F"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "J"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "K"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "V"] <- "A"

filtered_data <- lacrime %>% filter(Vict.Descent == "W")

dates_for_letter_A <- filtered_data$DATE.OCC

filtered_data$DATE.OCC <- as.Date(filtered_data$DATE.OCC)

summary_data <- filtered_data %>%
  group_by(DATE.OCC) %>%
  summarize(Count = n())

plot(summary_data$DATE.OCC, summary_data$Count, type = "p", pch = 1, cex = 0.4,
     col = "blue", xlab = "Date Occurred", ylab = "Number of Victims", 
     main = "Number of White Victims Daily in Los Angeles 2020", mgp = c(3, 1, 0),
     xaxt = "n", yaxt = "n")
axis(1, at = seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), 
     labels = format(seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), "%b %Y"), cex.axis = 0.4)
axis(2, las = 0, cex.axis = 0.4)

#lockdown_date <- as.Date("2020-03-19")
#text(x = lockdown_date, y = max(summary_data$Count), labels = "Lockdown 3/19", pos = 1, offset = 1, cex = 0.4)

#travel_ban <- as.Date("2020-01-31")
#text(x = travel_ban, y = 39, labels = "Travel Ban 1/31", pos = 1, offset = 1, cex = 0.4)

model <- lm(summary_data$Count ~ as.numeric(summary_data$DATE.OCC))
abline(model, col = "red")
```

```{r}
#lacrime <- lacrime[2:148206, ]
lacrime$Vict.Descent[lacrime$Vict.Descent == ""] <- "X"
lacrime$Vict.Descent[lacrime$Vict.Descent == "C"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "F"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "J"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "K"] <- "A"
lacrime$Vict.Descent[lacrime$Vict.Descent == "V"] <- "A"

filtered_data <- lacrime %>% filter(Vict.Descent == "B")

dates_for_letter_A <- filtered_data$DATE.OCC

filtered_data$DATE.OCC <- as.Date(filtered_data$DATE.OCC)

summary_data <- filtered_data %>%
  group_by(DATE.OCC) %>%
  summarize(Count = n())

plot(summary_data$DATE.OCC, summary_data$Count, type = "p", pch = 1, cex = 0.4,
     col = "blue", xlab = "Date Occurred", ylab = "Number of Victims", 
     main = "Number of Black Victims Daily in Los Angeles 2020", mgp = c(3, 1, 0),
     xaxt = "n", yaxt = "n")
axis(1, at = seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), 
     labels = format(seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), "%b %Y"), cex.axis = 0.4)
axis(2, las = 0, cex.axis = 0.4)

#lockdown_date <- as.Date("2020-03-19")
#text(x = lockdown_date, y = max(summary_data$Count), labels = "Lockdown 3/19", pos = 1, offset = 1, cex = 0.4)

#travel_ban <- as.Date("2020-01-31")
#text(x = travel_ban, y = 39, labels = "Travel Ban 1/31", pos = 1, offset = 1, cex = 0.4)

model <- lm(summary_data$Count ~ as.numeric(summary_data$DATE.OCC))
abline(model, col = "red")
```

