---
title: "Practice"
author: "Grant Powell"
date: "2023-12-05"
output: 
  flexdashboard::flex_dashboard:
  vertical_layout: scroll
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(dplyr)
library(readxl)
lacrime <- read_xlsx("/Users/thefinas1/Documents/lacrime.xlsx")
```

### Chart 1

```{r, echo=FALSE}
lacrime2020 <- lacrime[2:148206, ]
lacrime2020$Vict.Descent[lacrime2020$Vict.Descent == ""] <- "X"
lacrime2020$Vict.Descent[lacrime2020$Vict.Descent == "C"] <- "A"
lacrime2020$Vict.Descent[lacrime2020$Vict.Descent == "F"] <- "A"
lacrime2020$Vict.Descent[lacrime2020$Vict.Descent == "J"] <- "A"
lacrime2020$Vict.Descent[lacrime2020$Vict.Descent == "K"] <- "A"
lacrime2020$Vict.Descent[lacrime2020$Vict.Descent == "V"] <- "A"

filtered_data <- lacrime2020 %>% filter(Vict.Descent == "A")

dates_for_letter_A <- filtered_data$DATE.OCC

filtered_data$DATE.OCC <- as.Date(filtered_data$DATE.OCC)

summary_data <- filtered_data %>%
  group_by(DATE.OCC) %>%
  summarize(Count = n())

plot(summary_data$DATE.OCC, summary_data$Count, type = "p", pch = 1, cex = 0.4,
     col = "blue", xlab = "Date Occurred", ylab = "Number of Victims", 
     main = "Number of Asian Victims Daily in Los Angeles 2020", mgp = c(3, 1, 0),
     xaxt = "n", yaxt = "n")
axis(1, at = seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), 
     labels = format(seq(min(summary_data$DATE.OCC), max(summary_data$DATE.OCC), by = "month"), "%b %Y"), cex.axis = 0.4)
axis(2, las = 0, cex.axis = 0.4)

lockdown_date <- as.Date("2020-03-19")
text(x = lockdown_date, y = max(summary_data$Count), labels = "Lockdown 3/19", pos = 1, offset = 1, cex = 0.4)

travel_ban <- as.Date("2020-01-31")
text(x = travel_ban, y = 39, labels = "Travel Ban 1/31", pos = 1, offset = 1, cex = 0.4)

model <- lm(summary_data$Count ~ as.numeric(summary_data$DATE.OCC))
abline(model, col = "red")

```

### Chart 2

```{r, echo=FALSE}
lacrime2021 <- lacrime[148207:303895, ]
lacrime2021$Vict.Descent[lacrime2021$Vict.Descent == ""] <- "X"
lacrime2021$Vict.Descent[lacrime2021$Vict.Descent == "C"] <- "A"
lacrime2021$Vict.Descent[lacrime2021$Vict.Descent == "F"] <- "A"
lacrime2021$Vict.Descent[lacrime2021$Vict.Descent == "J"] <- "A"
lacrime2021$Vict.Descent[lacrime2021$Vict.Descent == "K"] <- "A"
lacrime2021$Vict.Descent[lacrime2021$Vict.Descent == "V"] <- "A"

# Filter the rows with "A" in the Vict.Descent column
filtered_data_2 <- lacrime2021 %>% filter(Vict.Descent == "A")

# Extract the dates from the filtered data
dates_for_letter_A_2 <- filtered_data_2$DATE.OCC

# Make sure the "Date Occurred" column is in the date format
filtered_data_2$DATE.OCC <- as.Date(filtered_data_2$DATE.OCC)

summary_data_2 <- filtered_data_2 %>%
  group_by(DATE.OCC) %>%
  summarize(Count = n())

# Create a time-series scatterplot
plot(summary_data_2$DATE.OCC, summary_data_2$Count, type = "p", pch = 1, cex = 0.4,
     col = "blue", xlab = "Date Occurred", ylab = "Number of Victims", 
     main = "Number of Asian Victims Daily in Los Angeles 2021", mgp = c(3, 1, 0),
     xaxt = "n", yaxt = "n")
axis(1, at = seq(min(summary_data_2$DATE.OCC), max(summary_data_2$DATE.OCC), by = "month"), 
     labels = format(seq(min(summary_data_2$DATE.OCC), max(summary_data_2$DATE.OCC), by = "month"), "%b %Y"), cex.axis = 0.4)
axis(2, las = 0, cex.axis = 0.4)

model <- lm(summary_data_2$Count ~ as.numeric(summary_data_2$DATE.OCC))
abline(model, col = "red")
```

### Chart 3

```{r, echo=FALSE}
lacrime2022 <- lacrime[303896:404565, ]
lacrime2022$Vict.Descent[lacrime2022$Vict.Descent == ""] <- "X"
lacrime2022$Vict.Descent[lacrime2022$Vict.Descent == "C"] <- "A"
lacrime2022$Vict.Descent[lacrime2022$Vict.Descent == "F"] <- "A"
lacrime2022$Vict.Descent[lacrime2022$Vict.Descent == "J"] <- "A"
lacrime2022$Vict.Descent[lacrime2022$Vict.Descent == "K"] <- "A"
lacrime2022$Vict.Descent[lacrime2022$Vict.Descent == "V"] <- "A"

filtered_data_3 <- lacrime2022 %>% filter(Vict.Descent == "A")

filtered_data_3$DATE.OCC <- as.Date(filtered_data_3$DATE.OCC)

filtered_data_3 <- filtered_data_3[order(filtered_data_3$DATE.OCC), ]

summary_data_3 <- filtered_data_3 %>%
  group_by(DATE.OCC) %>%
  summarize(Count = n())

# Create a time-series scatterplot with no x-axis labels
plot(summary_data_3$DATE.OCC, summary_data_3$Count, type = "p", pch = 1, cex = 0.4,
     col = "blue", xlab = "Date Occurred", ylab = "Number of Victims", 
     main = "Number of Asian Victims Daily in Los Angeles 2022", mgp = c(3, 1, 0), 
     xaxt = "n", yaxt = "n")
axis(1, at = seq(min(summary_data_3$DATE.OCC), max(summary_data_3$DATE.OCC), by = "month"), 
     labels = format(seq(min(summary_data_3$DATE.OCC), max(summary_data_3$DATE.OCC), by = "month"), "%b %Y"), cex.axis = 0.6)
axis(2, las = 0, cex.axis = 0.6)

model <- lm(summary_data_3$Count ~ as.numeric(summary_data_3$DATE.OCC))
abline(model, col = "red")
```

------------------------------------------------------------------------
