---
title: "grants_project_barcharts"
author: "Grant Powell"
date: "2023-12-08"
output:
  flexdashboard::flex_dashboard:
  vertical-layout: scroll
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(lubridate)
library(flexdashboard)

lacrime <- read_xlsx("/Users/thefinas1/Documents/lacrime.xlsx")
```

### Chart 1

```{r, echo=FALSE}
lacrime2020 <- lacrime[2:148206, ]
lacrime2020$Vict.Descent[lacrime2020$Vict.Descent == ""] <- "X"

# Filter out rows with the year 2021
lacrime2020 <- lacrime2020 %>%
  filter(year(as.Date(Month)) != 2021)

# Filter the rows with "A" in the Vict.Descent column
filtered_data_B <- lacrime2020 %>% filter(Vict.Descent == "B")

# Extract the dates from the filtered data
dates_for_letter_B <- filtered_data_B$Month

# Make sure the "Date Occurred" column is in the date format
filtered_data_B$Month <- as.Date(filtered_data_B$Month)

summary_data_B <- filtered_data_B %>%
  group_by(Month) %>%
  summarize(Count = n())

barplot(summary_data_B$Count,
     col = "yellow", xlab = "Month", ylab = "Number of Victims", 
     main = "Number of Black Victims Monthly in Los Angeles 2020", 
     names.arg = format(summary_data_B$Month, "%b"))
```

### Chart 2

```{r, echo=FALSE}
lacrime2021 <- lacrime[148207:303895, ]
lacrime2021$Vict.Descent[lacrime2021$Vict.Descent == ""] <- "X"

# Filter the rows with "A" in the Vict.Descent column
filtered_data_B_2 <- lacrime2021 %>% filter(Vict.Descent == "B")

# Extract the dates from the filtered data
dates_for_letter_B_2 <- filtered_data_B_2$Month

# Make sure the "Date Occurred" column is in the date format
filtered_data_B_2$Month <- as.Date(filtered_data_B_2$Month)

summary_data_B_2 <- filtered_data_B_2 %>%
  group_by(Month) %>%
  summarize(Count = n())

barplot(summary_data_B_2$Count,
     col = "yellow", xlab = "Month", ylab = "Number of Victims", 
     main = "Number of Black Victims Monthly in Los Angeles 2021", 
     names.arg = format(summary_data_B_2$Month, "%b"))

```

### Chart 3

```{r, echo=FALSE}
lacrime2022 <- lacrime[303896:404565, ]
lacrime2022$Vict.Descent[lacrime2022$Vict.Descent == ""] <- "X"

# Filter the rows with "A" in the Vict.Descent column
filtered_data_B_3 <- lacrime2022 %>% filter(Vict.Descent == "B")

# Extract the dates from the filtered data
dates_for_letter_B_3 <- filtered_data_B_3$Month

# Make sure the "Date Occurred" column is in the date format
filtered_data_B_3$Month <- as.Date(filtered_data_B_3$Month)

summary_data_B_3 <- filtered_data_B_3 %>%
  group_by(Month) %>%
  summarize(Count = n())

barplot(summary_data_B_3$Count,
     col = "yellow", xlab = "Month", ylab = "Number of Victims", 
     main = "Number of Black Victims Monthly in Los Angeles 2022", 
     names.arg = format(summary_data_B_3$Month, "%b"))
```

### Chart 4

```{r, echo=FALSE}
lacrime2020_A <- lacrime[2:148206, ]
lacrime2020_A$Vict.Descent[lacrime2020_A$Vict.Descent == ""] <- "X"
lacrime2020_A$Vict.Descent[lacrime2020_A$Vict.Descent %in% c("C", "F", "J", "K", "V")] <- "A"

lacrime2020_A <- lacrime2020_A %>%
  filter(year(as.Date(Month)) != 2021)

filtered_data_A <- lacrime2020_A %>% filter(Vict.Descent == "A")

dates_for_letter_A <- filtered_data_A$Month

filtered_data_A$Month <- as.Date(filtered_data_A$Month)

summary_data_A <- filtered_data_A %>%
  group_by(Month) %>%
  summarize(Count = n())

barplot(summary_data_A$Count, xlab = "Month", ylab = "Number of Victims", 
        main = "Asian Victims Monthly in Los Angeles 2020", 
        names.arg = format(summary_data_A$Month, "%b"), col = "red")
```

### Chart 5

```{r, echo=FALSE}
lacrime2021_A <- lacrime[148207:303895,  ]
lacrime2021_A$Vict.Descent[lacrime2021_A$Vict.Descent == ""] <- "X"
lacrime2021_A$Vict.Descent[lacrime2021_A$Vict.Descent %in% c("C", "F", "J", "K", "V")] <- "A"

filtered_data_A_2 <- lacrime2021_A %>% filter(Vict.Descent == "A")

filtered_data_A_2$Month <- as.Date(filtered_data_A_2$Month)

summary_data_A_2 <- filtered_data_A_2 %>%
  group_by(Month) %>%
  summarize(Count = n())

barplot(summary_data_A_2$Count, xlab = "Month", ylab = "Number of Victims", 
        main = "Asian Victims Monthly in Los Angeles 2021", 
        names.arg = format(summary_data_A_2$Month, "%b"), col = "red")
```

### Chart 6

```{r, echo=FALSE}
lacrime2022_A <- lacrime[303896:404565, ]
lacrime2022_A$Vict.Descent[lacrime2022_A$Vict.Descent == ""] <- "X"
lacrime2022_A$Vict.Descent[lacrime2022_A$Vict.Descent %in% c("C", "F", "J", "K", "V")] <- "A"

filtered_data_A_3<- lacrime2022_A %>% filter(Vict.Descent == "A")

filtered_data_A_3$Month <- as.Date(filtered_data_A_3$Month)

summary_data_A_3<- filtered_data_A_3 %>%
  group_by(Month) %>%
  summarize(Count = n())

barplot(summary_data_A_3$Count, xlab = "Month", ylab = "Number of Victims", 
        main = "Asian Victims Monthly in Los Angeles 2022", 
        names.arg = format(summary_data_A_3$Month, "%b"), col = "red")
```

### Chart 7

```{r, echo=FALSE}
lacrime202122 <- lacrime
lacrime202122$Vict.Descent[lacrime202122$Vict.Descent == ""] <- "X"

# Filter the rows with "B" in the Vict.Descent column
filtered_data_B_4 <- lacrime202122 %>% filter(Vict.Descent == "B")

# Extract the year from the "Month" column
filtered_data_B_4$Year <- as.factor(format(as.Date(filtered_data_B_4$Month), "%Y"))

# Summarize the counts by year
summary_data_B_4 <- table(filtered_data_B_4$Year)

# Bar plot using base R graphics
barplot(summary_data_B_4, col = "yellow", 
        xlab = "Year", ylab = "Number of Victims",
        main = "Number of Black Victims by Year in Los Angeles 2020-2022")
```

### Chart 8

```{r, echo=FALSE}
lacrime202122_A <- lacrime
lacrime202122_A$Vict.Descent[lacrime202122_A$Vict.Descent == ""] <- "X"
lacrime202122_A$Vict.Descent[lacrime202122_A$Vict.Descent %in% c("C", "F", "J", "K", "V")] <- "A"

filtered_data_A_4 <- lacrime202122_A %>% filter(Vict.Descent == "A")

filtered_data_A_4$Month <- as.Date(filtered_data_A_4$Month)

summary_data_A_4 <- filtered_data_A_4 %>%
  group_by(Year = year(Month)) %>%
  summarize(Count = n())

barplot(summary_data_A_4$Count, 
        names.arg = summary_data_A_4$Year,  # Specify the names for each bar
        xlab = "Year", ylab = "Number of Victims", 
        main = "Number of Asian Victims Yearly in Los Angeles 2020-2022", col = "red")
```

------------------------------------------------------------------------